### ISSUE TITLE
关于GaussianAvatars

### ISSUE THREAD

**Issue by Time-Lord12th** [ZCB-endeavor/OGL_PointCloud#1]
抱歉在这提一个无关issue。您在[GaussianAvatars](https://github.com/ShenhanQian/GaussianAvatars)提的问题解决了吗？我最近也在尝试用colmap的结果进行初始化。

**Comment by ZCB-endeavor** [comment]
你可以参考这个[issue](https://github.com/ShenhanQian/GaussianAvatars/issues/9)提到的转换方式，将colmap坐标系转换为所需的坐标系，但是还相差尺度因子，这个需要你根据两个坐标系下的点进行计算。

**Comment by Time-Lord12th** [comment]
非常感谢！您是用colmap数据进行gs的初始化吗？[https://github.com/ShenhanQian/GaussianAvatars/issues/19](https://github.com/ShenhanQian/GaussianAvatars/issues/19)是不是除了colmap的坐标系转换外，还需要解决这个数据读取的问题。

**Comment by ZCB-endeavor** [comment]
官方还并未开源数据预处理的脚本，不过你可以参考官方开放的数据集格式编写数据预处理脚本送入GaussianAvatars进行训练。我认为官方的数据并不是按照colmap格式或者传统gaussian splatting组织的。

**Comment by Time-Lord12th** [comment]
看起来有点小坑，我还是换个直接基于colmap重建gs的code。这个本身就是基于FLAME绑定gs的，感觉再改回去有点绕远路了。
谢谢您的解答！

**Comment by ZCB-endeavor** [comment]
没事儿，GaussianAvatars是基于FLAME网格模型进行的训练，不过原版的[gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting)能够直接根据colmap的结果进行场景的训练，只不过要根据高斯的结果导出网格模型较为困难。

**Comment by Time-Lord12th** [comment]
嗯嗯。可能之后会有类似neus那样，把gs和sdf结合起来的工作吧
